# Generated by Django 4.2.5 on 2023-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d"),
        ),
    ]
